basePath: /
definitions:
  domain.Usuario:
    properties:
      email:
        type: string
      id:
        type: integer
      nome:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: seu.email@provedor.com
    name: Seu Nome
    url: https://seulinkedin.com/in/seu-usuario
  description: Esta é uma API completa para gerenciamento de usuários, como parte
    de um projeto de portfólio.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API de Usuários
  version: "1.0"
paths:
  /usuarios:
    get:
      description: Retorna uma lista com todos os usuários cadastrados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Usuario'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todos os usuários
      tags:
      - usuarios
    post:
      consumes:
      - application/json
      description: Adiciona um novo usuário ao banco de dados com base nos dados fornecidos
      parameters:
      - description: Dados do usuário para criação
        in: body
        name: usuario
        required: true
        schema:
          $ref: '#/definitions/domain.Usuario'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Usuario'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo usuário
      tags:
      - usuarios
  /usuarios/{id}:
    delete:
      description: Remove um usuário do banco de dados com base no seu ID
      parameters:
      - description: ID do Usuário
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deleta um usuário
      tags:
      - usuarios
    get:
      description: Retorna os dados de um usuário específico com base no seu ID
      parameters:
      - description: ID do Usuário
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Usuario'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Busca um usuário por ID
      tags:
      - usuarios
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um usuário existente com base no seu ID
      parameters:
      - description: ID do Usuário
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do usuário para atualização
        in: body
        name: usuario
        required: true
        schema:
          $ref: '#/definitions/domain.Usuario'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Atualiza um usuário
      tags:
      - usuarios
swagger: "2.0"
